[project]
name = "vllmulator"
version = "0.1.0"
description = "A calculator for determining parallelism requirements for running models with vllm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.32.4",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
